flow/config/routes.rb
Flow::Application.routes.draw do

  match "/report_data_entry"                     => "reports#report_data_entry"
  match "/report_data_completeness"              => "reports#report_data_completeness"
  get "chart/org_context"
  get "chart/org_context_print"

  # match "/chart/org_context"          => "chart#org_context"

  resources :portfolios
  resources :plans
  resources :milestones
  resources :resource_allocations

  resources :people do
    collection do
      match 'search' => 'people#search', :via => [:get, :post], :as => :search

      get :edit_multiple
      put :update_multiple
    end
  end


  resources :person_associations

  # devise_for :users
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  resources :widgets do
    resources :parts
  end

  resources :employees do
    collection do
      match 'search' => 'employees#search', :via => [:get, :post], :as => :search
    end
  end
  resources :reporting_relationships

  get "home/index"

  match "/release_calendar"          => "home#release_calendar"

  match "/orgchart"                  => "home#orgchart"                            # deprecated

  match "/people_tree"               => "home#people_tree"                         # people
  match "/people_tree_data"          => "home#people_tree_data"                    # people, json

  match "/orgdendro"                 => "home#orgdendro"                           # employees
  match "/orgdendro_tree"            => "home#orgdendro_tree"                      # employees, json

  match "/staffingchart"             => "home#staffingchart"

  match "/budgetchart"               => "home#budgetchart"
  match "/budgetchart_dynamic"       => "home#budgetchart_dynamic"


  root :to => 'home#index'

end

flow/app/models/person.rb
class Person < ActiveRecord::Base
  include DirtyAssociations

  @person_types = ['employee', 'contractor']
  @hr_statuses = ['active', 'resigned']
  @hiring_statuses = ['requested', 'approved / not posted', 'approved / posted', 'unbudgeted / posted', 'hired']
  @budgets = ['Budget A', 'Budget B', 'Budget C', 'Budget D', 'Budget F', 'Budget G']
  @location_floors = [
    '7 North', '7 South', '7 East', '7 West', '8 North', '8 South', '8 East', '8 West', '9 North', '9 South', '9 East', '9 West', '10 North', '10 South', '10 East', '10 West',
    '11 North', '11 South', '11 East', '11 West', '12 North', '12 South', '12 East', '12 West', '13 North', '13 South', '13 East', '13 West'
  ]
  @person_roles = ['Software Engineer', 'Systems Engineer', 'Quality Assurance', 'Project Management', 'Other']
  @person_foci = ['Information Worker', 'People Management', 'Other']

  @groups = [
    'Ad Ops',
    'Business Development',
    'Business Intelligence',
    'CMS',
    'Digital Paid Products',
    'Ecommerce & Customer Service',
    'Ecommerce UI Engineering',
    'Emerging Technologies',
    'Finance',
    'Information Security',
    'Infrastructure Engineering',
    'Interactive Technology',
    'Index',
    'New Products',
    'Planning',
    'Platform Technologies',
    'Product Management',
    'Project Management',
    'Quality Assurance',
    'Systems & Infrastructure',
    'Technology Management',
    'Web & Mobile Engineering',
    'Web Technologies'
  ]

  @seatings = ['offsite', 'hotel', 'hotel w/home', 'home']

  class << self
    attr_accessor :person_types, :hr_statuses, :hiring_statuses, :budgets, :groups, :seatings, :location_floors, :person_roles, :person_foci
  end

  attr_accessible :id, :name, :title, :person_type, :temporary, :hr_status, :part_time, :cost_center, :business_unit,
  :direct_subordinate_tokens, :dotted_subordinate_tokens, :direct_supervisor_tokens, :dotted_supervisor_tokens,
  :location_floor, :location_code, :hiring_status, :seating, :employment_start_date, :employment_end_date, :budget,
  :group, :office_phone, :cell_phone, :person_role, :person_focus, :peoplesoft_title, :customer_tokens

  validates_presence_of :name, :title, :person_type

  validates :person_type,   :inclusion => { :in => @person_types,        :message => "%{value} is not a valid person type" }
  #validates :hr_status,     :inclusion => { :in => @hr_statuses,         :message => "%{value} is not a valid HR status" }
  #validates :hiring_status, :inclusion => { :in => @hiring_statuses,     :message => "%{value} is not a valid hiring status" }

  #validates :budget,        :inclusion => { :in => @budgets,             :message => "%{value} is not a valid budget" }
  #validates :group,         :inclusion => { :in => @groups,              :message => "%{value} is not a valid group" }
  #validates :seating,       :inclusion => { :in => @seatings,            :message => "%{value} is not a valid seating" }

  validates :part_time,     :inclusion => { :in => [true, false] }
  validates :temporary,     :inclusion => { :in => [true, false] }

  before_validation :checks

  has_many :source_associations, :class_name => "PersonAssociation",  :foreign_key => :sink_id,    :dependent => :destroy,  :after_add => :make_dirty, :after_remove => :make_dirty
  has_many :sink_associations,   :class_name => "PersonAssociation",  :foreign_key => :source_id,  :dependent => :destroy,  :after_add => :make_dirty, :after_remove => :make_dirty

  has_many :resource_allocations, :dependent => :destroy

  has_many :sources, :through => :source_associations, :after_add => :make_dirty, :after_remove => :make_dirty
  has_many :sinks,   :through => :sink_associations,   :after_add => :make_dirty, :after_remove => :make_dirty

  has_one :user

  #def initialize(attributes={})
  #  super
  #  @person_type   ||= :employee
  #  @hr_status     ||= :active
  #  logger.info "initialize values: #{self.inspect}"
  #end

  ################################################################################################
  # start custom validations, update hooks
  #
  def checks
    #logger.info "checks"
    #logger.info self.person_type
    #logger.info self.person_type.class
  end

  validate :miscellaneous_rules
  def miscellaneous_rules
    # todo -- add complex inter-field rules here
    # errors.add(:expiration_date, "can't be in the past")
  end

  before_save :adjust_attributes
  def adjust_attributes
    # in the event that some fields must change based upon other values, set here..
  end
  #
  # end custom validations, update hooks
  ################################################################################################

  #
  # csv export support
  #
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |person|
        csv << person.attributes.values_at(*column_names)
      end
    end
  end

  # customer accessors
  def add_customer(person); self.source_associations.build( { :association_type => 'reporting', :source_id => person.id, :sink_id => self.id } ); end
  scope :customers, lambda { |person| person.source_associations.where(:association_type => :customer_reporting).map { |ds| ds.source } }
  def customers; self.class.customers(self); end


  # direct supervisor accessors
  def add_direct_supervisor(person); self.source_associations.build( { :association_type => 'direct_reporting', :source_id => person.id, :sink_id => self.id } ); end
  scope :direct_supervisors, lambda { |person| person.source_associations.where(:association_type => :direct_reporting).map { |ds| ds.source } }
  def direct_supervisors; self.class.direct_supervisors(self); end

  # dotted supervisor accesors
  def add_dotted_supervisor(person); self.source_associations.build( { :association_type => 'dotted_reporting', :source_id => person.id, :sink_id => self.id } ); end
  scope :dotted_supervisors, lambda { |person| person.source_associations.where(:association_type => :dotted_reporting).map { |ds| ds.source } }
  def dotted_supervisors; self.class.dotted_supervisors(self); end

  # direct subordinate accessors
  def add_direct_subordinate(person); self.sink_associations.build( { :association_type => 'direct_reporting', :source_id => self.id, :sink_id => person.id } ); end
  scope :direct_subordinates, lambda { |person| person.sink_associations.where(:association_type => :direct_reporting).map { |ds| ds.sink } }
  def direct_subordinates; self.sink_associations.where(:association_type => :direct_reporting).map { |ds| ds.sink }; end

  # dotted subordinate accessors
  def add_dotted_subordinate(person); self.sink_associations.build( { :association_type => 'dotted_reporting', :source_id => self.id, :sink_id => person.id } ); end
  scope :dotted_subordinates, lambda { |person| person.sink_associations.where(:association_type => :dotted_reporting).map { |ds| ds.sink } }
  def dotted_subordinates; self.class.dotted_subordinates(self); end

  # jquery-token-input related

  def customer_tokens
    Person.customers(self).map { |ds| ds.id }
  end

  def customer_tokens=(ids)
    returned_ids = ids.split(",").flatten.uniq.collect{ |s| s.to_i }
    current_ids  = self.customers.collect { |s| s.id }
    to_be_added = returned_ids - current_ids
    to_be_removed = current_ids - returned_ids
    to_be_added.each { |s| self.source_associations.build(:association_type => 'customer_reporting', :source_id => s, :sink_id => self.id) }
    to_be_removed.each {|s| self.sources.delete( self.class.where(:id => s)) }
  end
  ##############################################################################################################################

  def direct_supervisor_tokens
    Person.direct_supervisors(self).map { |ds| ds.id }
  end

  def direct_supervisor_tokens=(ids)
    returned_ids = ids.split(",").flatten.uniq.collect{ |s| s.to_i }
    current_ids  = self.direct_supervisors.collect { |s| s.id }
    to_be_added = returned_ids - current_ids
    to_be_removed = current_ids - returned_ids
    to_be_added.each { |s| self.source_associations.build(:association_type => 'direct_reporting', :source_id => s, :sink_id => self.id) }
    to_be_removed.each {|s| self.sources.delete( self.class.where(:id => s)) }
  end

  def dotted_supervisor_tokens
    Person.dotted_supervisors(self).map { |ds| ds.id }
  end

  def dotted_supervisor_tokens=(ids)
    returned_ids = ids.split(",").flatten.uniq.collect{ |s| s.to_i }
    current_ids  = self.dotted_supervisors.collect { |s| s.id }
    to_be_added = returned_ids - current_ids
    to_be_removed = current_ids - returned_ids
    to_be_added.each { |s| self.source_associations.build(:association_type => 'dotted_reporting', :source_id => s, :sink_id => self.id) }
    to_be_removed.each {|s| self.sources.delete( self.class.where(:id => s)) }
  end

  def direct_subordinate_tokens
    Person.direct_subordinates(self).map { |ds| ds.id }
  end

  def direct_subordinate_tokens=(ids)
    returned_ids = ids.split(",").flatten.uniq.collect{ |s| s.to_i }
    current_ids  = self.direct_subordinates.collect { |s| s.id }
    to_be_added = returned_ids - current_ids
    to_be_removed = current_ids - returned_ids
    to_be_added.each { |s| self.sink_associations.build(:association_type => 'direct_reporting', :source_id => self.id, :sink_id => s) }
    to_be_removed.each {|s| self.sinks.delete( self.class.where(:id => s)) }
  end

  def dotted_subordinate_tokens
    Person.dotted_subordinates(self).map { |ds| ds.id }
  end

  def dotted_subordinate_tokens=(ids)
    returned_ids = ids.split(",").flatten.uniq.collect{ |s| s.to_i }
    current_ids  = self.dotted_subordinates.collect { |s| s.id }
    to_be_added = returned_ids - current_ids
    to_be_removed = current_ids - returned_ids
    to_be_added.each { |s| self.sink_associations.build(:association_type => 'dotted_reporting', :source_id => self.id, :sink_id => s) }
    to_be_removed.each {|s| self.sinks.delete( self.class.where(:id => s)) }
  end



end

flow/app/controllers/people_controller.rb
class PeopleController < InheritedResources::Base

  load_and_authorize_resource

  def search
    index
  end

  def index
    if params[:jqst] # being called from jquery token input plugin (expecting json)
      ppl = Person.where("name like ?", "%#{params[:jqst]}%")
      ppl.each {|p|
        if p.hr_status == 'resigned'
          p.name = p.name + " (Resigned)"
        elsif p.hiring_status != 'hired'
          p.name = p.name + " (Open)"
        end
      }
      @people = ppl
    else
      @search_params = params[:q]
      logger.info "people#index: search params: -- #{params[:q]} --"

      @search = Person.search(params[:q])
      ppl = @search.result
      @ppl_count = ppl.size
      if request.format == 'text/html'
        @people = ppl.paginate(:per_page => 15, :page => params[:page])
      else
        @people = ppl
      end
      @search.build_condition if @search.conditions.empty?
      @search.build_sort if @search.sorts.empty?
    end
    respond_to do |format|
      format.html { render :template => 'people/index' }
      format.json { render json: @people.map(&:attributes) }
      format.csv { send_data @people.to_csv }
      format.xls
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      post_activity nil, "viewed person #{@person.name}"
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end


  ###################### system writes ############################

  def post_activity(object, summary)
    activity = Activity.new
    activity.owner = User.find(current_user).email
    #activity.summary = "#{summary}: #{object.changed if !object.nil?}" TODO - get this working
    activity.summary = "#{summary}"
    activity.save!
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
        post_activity @person, "created person #{@person.name}"
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
        post_activity @person, "updated person #{@person.name}"
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    person_name = @person.name
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
      post_activity @person, "deleted person #{person_name}"
    end
  end

  def edit_multiple
    if !params[:person_ids]
      respond_to do |format|
        format.html { redirect_to people_path, notice: "Nobody was checked!!" }
      end
    else
      @people = Person.find(params[:person_ids])
    end
  end

  def update_multiple
    @people = Person.find(params[:person_ids])
    @people.reject! do |person|
      post_activity person, "updated person #{person.name}"
      person.update_attributes(params[:person].reject { |k,v| v.blank? })
    end
    if @people.empty?
      redirect_to people_url, notice: "People successfully updated."
    else
      @person = Person.new(params[:person])
      render "edit_multiple"
    end
  end

end

flow/app/helpers/people_helper.rb
module PeopleHelper

  def b(field)
    if field.nil? || field.size == 0
      '.'
    else
      field
    end
  end

end

flow/app/views/people/_condition_fields.html.erb
<div class="form-inline">

  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:sources] %>
  <% end %>

  <%= f.predicate_select compounds: false %>

  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>

  <small>
    <%= link_to "remove", '#' %>
  </small>

</div>

flow/app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1>Edit Person</h1>
</div>

<%= render :partial => 'form' %>

flow/app/views/people/edit_multiple.html.erb
<h1>Edit Checked People</h1>

<%= form_tag update_multiple_people_path, method: :put do %>
  <ul>
  <% @people.each do |person| %>
    <li>
      <%= hidden_field_tag "person_ids[]", person.id %>
      <%= person.name %>
      <ul class="errors">
        <% person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
  </ul>

  <%= simple_fields_for :person do |f| %>

  <!-- person type -->
  <%= f.input :person_type, collection: Person.person_types, :include_blank => true %>

  <!-- group -->
  <%= f.input :group, collection: Person.groups, :include_blank => true %>

  <!-- person role -->
  <%= f.input :person_role, collection: Person.person_roles, :include_blank => true %>

  <!-- person focus -->
  <%= f.input :person_focus, collection: Person.person_foci, :include_blank => true %>

  <!-- location floor -->
  <%= f.input :location_floor, collection: Person.location_floors, :include_blank => true %>

  <!-- seating -->
  <%= f.input :seating, collection: Person.seatings, :include_blank => true %>

  <!-- 
  <div class="field">
    <%= f.label :cell_phone %><br />
    <%= f.text_field :cell_phone %>
  </div>
  -->

  <% end %>

  <div class="form-actions">
    <%= submit_tag "Update", :class => "btn" %>
    <%= link_to 'Back', people_path, :class => "btn"  %>
  </div>

<% end %>

flow/app/views/people/index.html.erb
<%- model_class = Person -%>

<div class="page-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to raw("<i class='icon-plus icon-white'></i> New Person"), new_person_path, :class => 'btn-large btn-primary pull-right' %>
  </h1>
  
  <small><div class="muted pull-left"><%= @ppl_count %> results</div> </small>
  
  <small><div class="pull-right"><%= link_to "CSV", people_path(format: "csv", :q => @search_params) %> | <%= link_to "Excel", people_path(format: "xls", :q => @search_params) %></div></small>
  
  <br>
</div>

<div id="people-search-section" class="well">
  <div class="close">x</div>  

  <%= search_form_for @search, :url => search_people_path, :class => "form-inline", :html => {:method => :post} do |f| %>
  
    <%= f.condition_fields do |c| %>
      <%= render "condition_fields", f: c %>
    <% end %>
    
    <p><%= link_to_add_fields raw("<small>Add Conditions</small>"), f, :condition %></p>
    
    <div class="form-inline">
      Sort<br>
      <%= f.sort_fields do |s| %>
        <%= s.sort_select %>
      <% end %>
    </div>

    <%= submit_tag "Search", :name => nil, :class => 'btn pull-right' %>

  <% end %>
    
</div>	

<div class="muted">

  <button id="show_people_search" class="btn pull-right"><i class="icon-search"></i> Search</button>
</div>

<script language="JavaScript">
    function toggle(source) {
	checkboxes = document.getElementsByName('person_ids[]');
	for(var i=0, n=checkboxes.length;i<n;i++) {
	    checkboxes[i].checked = source.checked;
	}
    }
</script>

<%= form_tag edit_multiple_people_path, method: :get do %>

<table id="search_results" class="table table-striped">

  <thead>
    <tr>      
      <th><input type="checkbox" onClick="toggle(this)" /></th>

      <th><%= sort_link @search, :id, "Id" %></th>
      <th><%= sort_link @search, :name, "Name" %></th>
      <th><%= sort_link @search, :title, "Title" %></th>

      <th><%= sort_link @search, :cost_center, "Cost Center" %></th>
      <th><%= sort_link @search, :location_floor, "Location" %></th>
      <th><%= sort_link @search, :office_phone, "Ext" %></th>

      <% if can?(:update, Person) %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>

	<% if can?(:update, person) %>
	<td><%= check_box_tag "person_ids[]", person.id %></td>
	<% else %>
	<td></td>
	<% end %>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.title %></td>

        <td><%= person.cost_center %></td>
        <td><%= person.location_floor %></td>
        <td><%= person.office_phone %></td>

        <td>

	  <% if can?(:update, person) %>
          <%= link_to 'Edit', edit_person_path(person), :class => 'btn btn-mini' %>
	  <% end %>

	  <% if can?(:destroy, person) %>
          <%= link_to t('.destroy', 
              :default => t("helpers.links.destroy")),
              person_path(person), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>
	  <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= submit_tag "Edit Checked", :class => "btn" %>

<% end %>


<%= will_paginate @people %>



<!--
<br>
--Backbone test---
<br>
<div id="people"></div>
<br>

<script type="text/javascript">
    $(function() {
	// Blog is the app name
	window.router = new Flow.Routers.PeopleRouter({people: <%= @people.to_json.html_safe -%>});
	Backbone.history.start();
    });
</script>
-->

flow/app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

flow/app/views/people/new.js.erb
//debugger;
$('#new_reporting_relationship_link').hide().after( '<%= j render("form") %>' );

flow/app/views/people/show.html.erb
<%- model_class = Person -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %> | <%= @person.name %></h1> 
</div>

<p>
<%= link_to "Org Chart", chart_org_context_path(:id => @person.id), :class => "btn btn-small btn-info", :method => :get %>
</p>

<table class="table">

<tr><td>
<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:name) %></dt><dd><%= @person.name %></dd>
  <dt><%= model_class.human_attribute_name(:title) %></dt><dd><%= @person.title %></dd>
  <dt><%= model_class.human_attribute_name(:group) %></dt><dd><%= b @person.group %></dd>
</dl>
</td>

<td>
<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:person_type) %></dt><dd><%= b @person.person_type %></dd>
  <dt><%= model_class.human_attribute_name(:person_role) %></dt><dd><%= b @person.person_role %></dd>
  <dt><%= model_class.human_attribute_name(:person_focus) %></dt><dd><%= b @person.person_focus %></dd>


<tr><td>
<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:budget) %></dt><dd><%= b @person.budget %></dd>
  <dt><%= model_class.human_attribute_name(:hr_status) %></dt><dd><%= b @person.hr_status %></dd>
  <dt><%= model_class.human_attribute_name(:hiring_status) %></dt><dd><%= b @person.hiring_status %></dd>
</dl>
</td>

<td>

<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:cost_center) %></dt><dd><%= b @person.cost_center %></dd>
  <dt><%= model_class.human_attribute_name(:business_unit) %></dt><dd><%= b @person.business_unit %></dd>
</dl>
</td></tr>

<tr><td colspan="2">
<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:seating) %></dt><dd><%= b @person.seating %></dd>
  <dt><%= model_class.human_attribute_name(:location_floor) %></dt><dd><%= b @person.location_floor %></dd>
  <dt><%= model_class.human_attribute_name(:location_code) %></dt><dd><%= b @person.location_code %></dd>
  <dt><%= model_class.human_attribute_name(:office_phone) %></dt><dd><%= b @person.office_phone %></dd>
  <dt><%= model_class.human_attribute_name(:cell_phone) %></dt><dd><%= b @person.cell_phone %></dd>
</dl>
</td></tr>

<tr><td colspan="2">
<dl class="dl-horizontal">
  <dt><%= model_class.human_attribute_name(:peoplesoft_title) %></dt><dd><%= b @person.peoplesoft_title %></dd>
  <dt><%= model_class.human_attribute_name(:part_time) %></dt><dd><% if @person.part_time %> <i class="icon-ok"></i> <% else %> <i class="icon-minus"></i> <% end %></dd>
  <dt><%= model_class.human_attribute_name(:temporary) %></dt><dd><% if @person.temporary %> <i class="icon-ok"></i> <% else %> <i class="icon-minus"></i> <% end %></dd>
</td></tr>

</table>

<!--
<br>
<br>
<br>
<p>
  <%= model_class.human_attribute_name(:employment_start_date) %>:<%= @person.employment_start_date %>
  <%= model_class.human_attribute_name(:employment_end_date) %>:<%= @person.employment_end_date %>
</p>
-->
<br>

<% if @person.source_associations.size > 0 %>
<strong><%= @person.name %> has the following customers:</strong>
<table class="table">
  <thead>
    <tr>
      <th style="width: 50%"></th>
      <th style="width: 50%"></th>
    </tr>
  </thead> 
  <% @person.source_associations.each do |sr| %>
  <% if sr.association_type == "customer_reporting" %>
  <tr><td><%= link_to sr.source.name, sr.source %></td><td class="muted"><em><%= sr.source.title %> (<%= sr.association_type.humanize %>)</td></tr>
  <% end %>
  <% end %>
</table>

<% else %>
<strong><%= @person.name %> does not have any customers.</strong>
<br><br><br>
<% end %>



<% if @person.source_associations.size > 0 %>
<strong><%= @person.name %> reports to:</strong>
<table class="table">
  <thead>
    <tr>
      <th style="width: 50%"></th>
      <th style="width: 50%"></th>
    </tr>
  </thead> 
  <% @person.source_associations.each do |sr| %>
  <% if sr.association_type == "direct_reporting" || sr.association_type == "dotted_reporting" %>
  <tr><td><%= link_to sr.source.name, sr.source %></td><td class="muted"><em><%= sr.source.title %> (<%= sr.association_type.humanize %>)</td></tr>
  <% end %>
  <% end %>
</table>

<% else %>
<strong><%= @person.name %> does not have any customers.</strong>
<br><br><br>
<% end %>



<% if @person.sink_associations.size > 0 %>
<strong>The following people report to <%= @person.name %>:</strong>
<table class="table">
  <thead>
    <tr>
      <th style="width: 50%"></th>
      <th style="width: 50%"></th>
    </tr>
  </thead> 
  <% @person.sink_associations.each do |sr| %>
  <% if sr.association_type == "direct_reporting" || sr.association_type == "dotted_reporting" %>
  <tr><td><%= link_to sr.sink.name, sr.sink %></td><td class="muted"><em><%= sr.sink.title %> (<%= sr.association_type.humanize %>)</td></tr>
  <% end %>
  <% end %>
</table>

<% else %>
<strong><%= @person.name %> does not have any reports.</strong>
<br><br><br>
<% end %>

<div class="form-actions">
  <%= link_to 'Back', people_path, :class => 'btn'  %>

  <% if can?(:update, @person) %>
  <%= link_to 'Edit', edit_person_path(@person), :class => 'btn' %>
  <% end %>

  <% if can?(:destroy, @person) %>
  <%= link_to 'Destroy', person_path(@person), :method => 'delete', :data => { :confirm => 'Confirm', :default => 'Are you sure?' }, :class => 'btn btn-danger' %>
  <% end %>

</div>