flow/config/routes.rb
Flow::Application.routes.draw do

  match "/report_data_entry"                     => "reports#report_data_entry"
  match "/report_data_completeness"              => "reports#report_data_completeness"
  get "chart/org_context"
  get "chart/org_context_print"

  # match "/chart/org_context"          => "chart#org_context"

  resources :portfolios
  resources :plans
  resources :milestones
  resources :resource_allocations

  resources :people do
    collection do
      match 'search' => 'people#search', :via => [:get, :post], :as => :search

      get :edit_multiple
      put :update_multiple
    end
  end


  resources :person_associations

  # devise_for :users
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  resources :widgets do
    resources :parts
  end

  resources :employees do
    collection do
      match 'search' => 'employees#search', :via => [:get, :post], :as => :search
    end
  end
  resources :reporting_relationships

  get "home/index"

  match "/release_calendar"          => "home#release_calendar"

  match "/orgchart"                  => "home#orgchart"                            # deprecated

  match "/people_tree"               => "home#people_tree"                         # people
  match "/people_tree_data"          => "home#people_tree_data"                    # people, json

  match "/orgdendro"                 => "home#orgdendro"                           # employees
  match "/orgdendro_tree"            => "home#orgdendro_tree"                      # employees, json

  match "/staffingchart"             => "home#staffingchart"

  match "/budgetchart"               => "home#budgetchart"
  match "/budgetchart_dynamic"       => "home#budgetchart_dynamic"


  root :to => 'home#index'

end

flow/app/models/plan.rb
class Plan < ActiveRecord::Base

  attr_accessible :description, :name, :portfolio_category, :milestones_attributes, :resource_allocations_attributes

  belongs_to :portfolio
  has_many :milestones

  accepts_nested_attributes_for :milestones, allow_destroy: true

  has_many   :resource_allocations, :dependent => :destroy

  accepts_nested_attributes_for :resource_allocations, allow_destroy: true

  def add_resource_allocation(person, quantity, comment)
    ra = ResourceAllocation.new
    ra.person = person
    ra.quantity = quantity
    ra.comment = comment
    self.resource_allocations << ra
  end

end

flow/app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base
end

flow/app/helpers/plans_helper.rb
module PlansHelper
end

flow/app/views/plans/_form.html.erb
<%= simple_form_for(@plan) do |f| %>

  <%= f.error_notification %>

  <table class="table" border="1">
    
    <tr>
      <td>
      <%= f.input :name %>
      <%= f.input :description, :input_html => { :rows => 3 } %>
      <%= f.input :portfolio_category %>
      </td>
    </tr>

    <tr>
      <td>
	<%= f.fields_for :milestones do |builder| %>
	<%= render 'milestone_fields', f: builder %>
      </td>
    </tr>

  </table>

  <% end %>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

flow/app/views/plans/_milestone_fields.html.erb
<table class="table" border="5">
  <tr>
    <td>
      <!-- milestone -->
      <%= f.label :name, "Milestone" %><%= f.text_field :name %>
    </td>
    <td>
      <%= f.label :_destroy, "Remove milestone" %><%= f.check_box :_destroy %>
    </td>
    <td>
      <tr>
	<td>
	  <table class="table" border="3">
	    <tr>
	      <th>* Resource Name</th>
	      <th>* Quantity</th>
	      <th>* Comment</th>
	    </tr>
	    <tr>
	    <%= f.fields_for :resource_allocations do |builder| %>
	    </tr>
	    <%= render 'resource_allocation_fields', f: builder %>
	    <% end %>
	    <%= link_to_add_associations "Add Resource", f, :resource_allocations %>
	  </table>
	</td>
      </tr>
    </td>
  </tr>
</table
>

flow/app/views/plans/_resource_allocation_fields.html.erb
<tr>
  <td>
    <%= f.input :resource_name, 
	input_html: { class: 'resource_allocation_resource_name', 
	data: {autocomplete_source: people_path} }
	%>
  </td>
  <td>
    <%= f.input :quantity, collection: [1, 0.5, 0.2] %>
  </td>
  <td>
    <%= f.input :comment %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", "#", class: "remove_fields" %>
  </td>
</tr>

flow/app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

flow/app/views/plans/index.html.erb
<%- model_class = Plan-%>

<div class="page-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to raw("<i class='icon-plus icon-white'></i> New Plan"), new_plan_path, :class => 'btn-large btn-primary pull-right' %>
  </h1>
</div>

<table class="table table-striped">

  <thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
    <tr>
      <td><%= link_to plan.id, plan_path(plan) %></td>
      <td><%= plan.name %></td>
      <td><%= plan.description %></td>
      <td><%= plan.portfolio_category %></td>
      <td>
	<%= link_to 'Edit', edit_plan_path(plan), :class => 'btn btn-mini' %>
	<%= link_to t('.destroy', :default => t("helpers.links.destroy")), 
	plan_path(plan), :method => :delete, 
	:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	:class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

flow/app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

flow/app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>

<p>
  <b>Description:</b>
  <%= @plan.description %>
</p>

<p>
  <b>Portfolio category:</b>
  <%= @plan.portfolio_category %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>