flow/config/routes.rb
Flow::Application.routes.draw do

  match "/report_data_entry"                     => "reports#report_data_entry"
  match "/report_data_completeness"              => "reports#report_data_completeness"
  get "chart/org_context"
  get "chart/org_context_print"

  # match "/chart/org_context"          => "chart#org_context"

  resources :portfolios
  resources :plans
  resources :milestones
  resources :resource_allocations

  resources :people do
    collection do
      match 'search' => 'people#search', :via => [:get, :post], :as => :search

      get :edit_multiple
      put :update_multiple
    end
  end


  resources :person_associations

  # devise_for :users
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  resources :widgets do
    resources :parts
  end

  resources :employees do
    collection do
      match 'search' => 'employees#search', :via => [:get, :post], :as => :search
    end
  end
  resources :reporting_relationships

  get "home/index"

  match "/release_calendar"          => "home#release_calendar"

  match "/orgchart"                  => "home#orgchart"                            # deprecated

  match "/people_tree"               => "home#people_tree"                         # people
  match "/people_tree_data"          => "home#people_tree_data"                    # people, json

  match "/orgdendro"                 => "home#orgdendro"                           # employees
  match "/orgdendro_tree"            => "home#orgdendro_tree"                      # employees, json

  match "/staffingchart"             => "home#staffingchart"

  match "/budgetchart"               => "home#budgetchart"
  match "/budgetchart_dynamic"       => "home#budgetchart_dynamic"


  root :to => 'home#index'

end

flow/app/models/person_association.rb
class PersonAssociation < ActiveRecord::Base

  @association_types = ['direct_reporting', 'dotted_reporting', 'customer_reporting']

  class << self
    attr_accessor :association_types
  end

  attr_accessible :description, :sink_id, :source_id, :association_type, :source, :sink

  belongs_to :source,   :class_name => "Person"
  belongs_to :sink,     :class_name => "Person"

  validates_presence_of :association_type
  validates_uniqueness_of :sink_id, :scope => [:source_id, :association_type]

  validates :association_type, :inclusion => { :in => @association_types, :message => "%{value} is not a valid person association type" }

end

flow/app/controllers/person_associations_controller.rb
class PersonAssociationsController < InheritedResources::Base
end

flow/app/helpers/person_associations_helper.rb
module PersonAssociationsHelper
end

flow/app/views/person_associations/_form.html.erb
<%= simple_form_for(@person_association) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :type %>
    <%= f.input :source_id %>
    <%= f.input :sink_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

flow/app/views/person_associations/edit.html.erb
<h1>Editing person_association</h1>

<%= render 'form' %>

<%= link_to 'Show', @person_association %> |
<%= link_to 'Back', person_associations_path %>

flow/app/views/person_associations/index.html.erb
<h1>Listing person_associations</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Type</th>
    <th>Source</th>
    <th>Sink</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person_associations.each do |person_association| %>
  <tr>
    <td><%= person_association.description %></td>
    <td><%= person_association.type %></td>
    <td><%= person_association.source_id %></td>
    <td><%= person_association.sink_id %></td>
    <td><%= link_to 'Show', person_association %></td>
    <td><%= link_to 'Edit', edit_person_association_path(person_association) %></td>
    <td><%= link_to 'Destroy', person_association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person association', new_person_association_path %>

flow/app/views/person_associations/new.html.erb
<h1>New person_association</h1>

<%= render 'form' %>

<%= link_to 'Back', person_associations_path %>

flow/app/views/person_associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @person_association.description %>
</p>

<p>
  <b>Type:</b>
  <%= @person_association.type %>
</p>

<p>
  <b>Source:</b>
  <%= @person_association.source_id %>
</p>

<p>
  <b>Sink:</b>
  <%= @person_association.sink_id %>
</p>


<%= link_to 'Edit', edit_person_association_path(@person_association) %> |
<%= link_to 'Back', person_associations_path %>