flow/config/routes.rb
Flow::Application.routes.draw do

  match "/report_data_entry"                     => "reports#report_data_entry"
  match "/report_data_completeness"              => "reports#report_data_completeness"
  get "chart/org_context"
  get "chart/org_context_print"

  # match "/chart/org_context"          => "chart#org_context"

  resources :portfolios
  resources :plans
  resources :milestones
  resources :resource_allocations

  resources :people do
    collection do
      match 'search' => 'people#search', :via => [:get, :post], :as => :search

      get :edit_multiple
      put :update_multiple
    end
  end


  resources :person_associations

  # devise_for :users
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  resources :widgets do
    resources :parts
  end

  resources :employees do
    collection do
      match 'search' => 'employees#search', :via => [:get, :post], :as => :search
    end
  end
  resources :reporting_relationships

  get "home/index"

  match "/release_calendar"          => "home#release_calendar"

  match "/orgchart"                  => "home#orgchart"                            # deprecated

  match "/people_tree"               => "home#people_tree"                         # people
  match "/people_tree_data"          => "home#people_tree_data"                    # people, json

  match "/orgdendro"                 => "home#orgdendro"                           # employees
  match "/orgdendro_tree"            => "home#orgdendro_tree"                      # employees, json

  match "/staffingchart"             => "home#staffingchart"

  match "/budgetchart"               => "home#budgetchart"
  match "/budgetchart_dynamic"       => "home#budgetchart_dynamic"


  root :to => 'home#index'

end

flow/app/models/milestone.rb
# todo: consider nested attributes

class Milestone < ActiveRecord::Base
  attr_accessible :business_driver, :description, :health, :name, :planned_finish, :planned_start, :status, :facing

  belongs_to :plan

end

flow/app/controllers/milestones_controller.rb
class MilestonesController < InheritedResources::Base
end

flow/app/helpers/milestones_helper.rb
module MilestonesHelper
end

flow/app/views/milestones/_form.html.erb
<%= simple_form_for(@milestone) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :facing, 
	collection: ['Internal', 'External'] %>
    <%= f.input :business_driver, 
	collection: ['Revenue (Subscriber or Ad)', 'Contractual / Compliance', 
	'Maintenance / Efficiency', 'Strategic (Blue Sky / Innovation)','Journalism', 
	'User Experience', 'Table Stakes (Competitive)', 'Support'] %>
    <%= f.input :status, 
	collection: ['Open', 'Upcoming Releases', 'In Development', 'Production Ready', 'In Production', 'Verified in Production'] %>
    <%= f.input :health, collection: ['Green', 'Yellow', 'Red'] %>
    <%= f.input :planned_start %>
    <%= f.input :planned_finish %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

flow/app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

flow/app/views/milestones/index.html.erb
<%- model_class = Milestone-%>

<div class="page-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
    <%= link_to raw("<i class='icon-plus icon-white'></i> New Milestone"), new_milestone_path, :class => 'btn-large btn-primary pull-right' %>
  </h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Int/Ext</th>
    <th>Name</th>
    <th>Status</th>
    <th>Health</th>
    <th>Finish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @milestones.each do |milestone| %>
    <tr>
      <td>
	<% if milestone.facing == "Internal" %>
	<span class="badge badge-warning">I</span>
	<% elsif milestone.facing == "External" %>
	<span class="badge badge-info">E</span>
	<% else %>
	-
	<% end %>
      </td>
      <td>
	<%= milestone.name %>
      </td>
      <td>
	<% if milestone.status == "Open" %>
	<span class="badge badge-default">Open</span>
	<% elsif milestone.status == "Upcoming Releases" %>
	<span class="badge badge-info">On Deck</span>
	<% elsif milestone.status == "In Development" || milestone.status == "Production Ready" || milestone.status == "In Production" %>
	<span class="badge badge-info">In Progress</span>
	<% elsif milestone.status == "Verified in Production" %>
	<span class="badge badge-success">Shipped</span>
	<% else %>
	-
	<% end %>
      </td>
      <td>
      <% if milestone.health == "Green" %>
      <span class="badge badge-success">G</span>
      <% elsif milestone.health == "Yellow" %>
      <span class="badge badge-warning">Y</span>
      <% elsif milestone.health == "Red" %>
      <span class="badge badge-important">R</span>
      <% else %>
      -
      <% end %>
      </td>
      <td><%= distance_of_time_in_words_to_now(milestone.planned_finish) %></td>
      <td>
	<%= link_to 'Edit', edit_milestone_path(milestone), :class => 'btn btn-mini' %>
	<%= link_to t('.destroy', :default => t("helpers.links.destroy")), 
	milestone_path(milestone), :method => :delete, 
	:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	:class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

flow/app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

flow/app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @milestone.name %>
</p>

<p>
  <b>Description:</b>
  <%= @milestone.description %>
</p>

<p>
  <b>Facing:</b>
  <%= @milestone.facing %>
</p>

<p>
  <b>Business driver:</b>
  <%= @milestone.business_driver %>
</p>

<p>
  <b>Status:</b>
  <%= @milestone.status %>
</p>

<p>
  <b>Health:</b>
  <%= @milestone.health %>
</p>

<p>
  <b>Planned start:</b>
  <%= @milestone.planned_start %>
</p>

<p>
  <b>Planned finish:</b>
  <%= @milestone.planned_finish %>
</p>


<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>